-- Story 3.3 fix: tabela medical_schools + seed de especialidades reais
-- Essa tabela foi criada via SQL direto e nunca teve migration formal.
-- Ref: deferred-work.md — "medical_schools tabela sem migration formal"

-- 1. Tabela medical_schools (lookup para combobox de cadastro)
CREATE TABLE IF NOT EXISTS public.medical_schools (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  abbreviation text NOT NULL,
  state text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_medical_schools_abbreviation ON public.medical_schools(abbreviation);

COMMENT ON TABLE public.medical_schools IS 'Lista de faculdades de medicina para combobox de cadastro';

-- 2. RLS — leitura pública (usado no signup sem autenticação)
ALTER TABLE public.medical_schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_schools FORCE ROW LEVEL SECURITY;

CREATE POLICY "anyone can read medical_schools"
  ON public.medical_schools FOR SELECT
  TO anon, authenticated
  USING (true);

-- Apenas admin pode inserir/atualizar/deletar
CREATE POLICY "admin can manage medical_schools"
  ON public.medical_schools FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

-- 3. Seed de especialidades médicas reconhecidas pelo CFM/CNRM
-- Lista completa das 55 especialidades com acesso direto ou via área de atuação
-- Ref: Resolução CFM nº 2.330/2023 + CNRM
INSERT INTO public.specialties (name) VALUES
  -- Acesso direto (R1)
  ('Cirurgia Geral'),
  ('Clínica Médica'),
  ('Ginecologia e Obstetrícia'),
  ('Medicina de Família e Comunidade'),
  ('Medicina de Emergência'),
  ('Pediatria'),
  ('Anestesiologia'),
  ('Dermatologia'),
  ('Infectologia'),
  ('Medicina do Trabalho'),
  ('Medicina Legal e Perícia Médica'),
  ('Medicina Preventiva e Social'),
  ('Neurologia'),
  ('Neurocirurgia'),
  ('Oftalmologia'),
  ('Ortopedia e Traumatologia'),
  ('Otorrinolaringologia'),
  ('Patologia'),
  ('Psiquiatria'),
  ('Radiologia e Diagnóstico por Imagem'),
  ('Radioterapia'),
  ('Genética Médica'),
  ('Medicina Nuclear'),
  ('Medicina Física e Reabilitação'),
  ('Acupuntura'),
  -- Pré-requisito Clínica Médica
  ('Cardiologia'),
  ('Endocrinologia e Metabologia'),
  ('Gastroenterologia'),
  ('Geriatria'),
  ('Hematologia e Hemoterapia'),
  ('Nefrologia'),
  ('Oncologia Clínica'),
  ('Pneumologia'),
  ('Reumatologia'),
  ('Alergia e Imunologia'),
  ('Nutrologia'),
  ('Medicina Intensiva'),
  ('Hepatologia'),
  -- Pré-requisito Cirurgia Geral
  ('Cirurgia Cardiovascular'),
  ('Cirurgia de Cabeça e Pescoço'),
  ('Cirurgia do Aparelho Digestivo'),
  ('Cirurgia Pediátrica'),
  ('Cirurgia Plástica'),
  ('Cirurgia Torácica'),
  ('Cirurgia Vascular'),
  ('Coloproctologia'),
  ('Urologia'),
  -- Pré-requisito Pediatria
  ('Neonatologia'),
  ('Medicina do Adolescente'),
  -- Pré-requisito GO
  ('Mastologia'),
  -- Outras com pré-requisito específico
  ('Cirurgia da Mão'),
  ('Cancerologia Cirúrgica'),
  ('Medicina do Esporte'),
  ('Medicina Intensiva Pediátrica'),
  ('Endoscopia')
ON CONFLICT (name) DO NOTHING;

-- 4. Seed completo de faculdades de medicina brasileiras
-- Fonte: lista oficial MEC/CNRM com todas as escolas médicas do Brasil
INSERT INTO public.medical_schools (name, abbreviation, state) VALUES
  -- ACRE
  ('Centro Universitário Uninorte - Rio Branco', 'UNINORTE', 'AC'),
  ('ITPAC Cruzeiro do Sul', 'ITPAC-CZS', 'AC'),
  ('Universidade Federal do Acre', 'UFAC', 'AC'),
  -- ALAGOAS
  ('Centro Universitário Cesmac - Maceió', 'CESMAC', 'AL'),
  ('Centro Universitário de Maceió', 'UNIMA', 'AL'),
  ('Universidade Estadual de Ciências da Saúde de Alagoas', 'UNCISAL', 'AL'),
  ('Universidade Federal de Alagoas - Arapiraca', 'UFAL-Arapiraca', 'AL'),
  ('Universidade Federal de Alagoas', 'UFAL', 'AL'),
  -- AMAZONAS
  ('Afya Faculdade de Ciências Médicas de Itacoatiara', 'AFYA ITACOATIARA', 'AM'),
  ('Afya Faculdade de Ciências Médicas de Manacapuru', 'AFYA MANACAPURU', 'AM'),
  ('Centro Universitário CEUNI-FAMETRO - Manaus', 'FAMETRO', 'AM'),
  ('Universidade do Estado do Amazonas - Manaus', 'UEA', 'AM'),
  ('Universidade Federal do Amazonas - Coari', 'UFAM-Coari', 'AM'),
  ('Universidade Federal do Amazonas', 'UFAM', 'AM'),
  ('Universidade Nilton Lins - Manaus', 'UNINILTONLINS', 'AM'),
  -- AMAPÁ
  ('Faculdade Integrado de Macapá', 'INTEGRADO-AP', 'AP'),
  ('Universidade Federal do Amapá', 'UNIFAP', 'AP'),
  -- BAHIA
  ('Afya Faculdade de Ciências Médicas de Itabuna', 'AFYA ITABUNA', 'BA'),
  ('Centro Universitário AGES', 'UniAGES', 'BA'),
  ('Centro Universitário Dom Pedro II', 'UNIDOMPEDRO', 'BA'),
  ('Centro Universitário UniFG - Guanambi', 'UniFG', 'BA'),
  ('Escola Bahiana de Medicina e Saúde Pública - Salvador', 'EBMSP', 'BA'),
  ('Faculdade AGES de Medicina - Jacobina', 'FAM-BA', 'BA'),
  ('Faculdade AGES de Medicina de Irecê', 'AGES-Irecê', 'BA'),
  ('Faculdade de Medicina Pitágoras de Eunápolis', 'Pitágoras-Eunápolis', 'BA'),
  ('Faculdade de Saúde Santo Agostinho - Vitória da Conquista', 'FASA', 'BA'),
  ('Faculdade de Tecnologia e Ciências - Salvador', 'FTC', 'BA'),
  ('Faculdade Estácio de Alagoinhas', 'Estácio-Alagoinhas', 'BA'),
  ('Faculdade Estácio de Juazeiro', 'Estácio-Juazeiro', 'BA'),
  ('Faculdades Integradas Padrão - Guanambi', 'FIP Guanambi', 'BA'),
  ('Universidade Federal do Vale do São Francisco - Paulo Afonso', 'UNIVASF-PA', 'BA'),
  ('Unime Lauro de Freitas', 'UNIME', 'BA'),
  ('Universidade do Estado da Bahia - Salvador', 'UNEB', 'BA'),
  ('Universidade Estadual de Feira de Santana', 'UEFS', 'BA'),
  ('Universidade Estadual de Santa Cruz - Ilhéus', 'UESC', 'BA'),
  ('Universidade Estadual do Sudoeste da Bahia - Jequié', 'UESB-Jequié', 'BA'),
  ('Universidade Estadual do Sudoeste da Bahia - Vitória da Conquista', 'UESB-VdC', 'BA'),
  ('Universidade Federal da Bahia - Anísio Teixeira', 'UFBA-CAT', 'BA'),
  ('Universidade Federal da Bahia', 'UFBA', 'BA'),
  ('Universidade Federal do Oeste da Bahia - Barreiras', 'UFOB', 'BA'),
  ('Universidade Federal do Recôncavo da Bahia', 'UFRB', 'BA'),
  ('Universidade Federal do Sul da Bahia - Teixeira de Freitas', 'UFSBA', 'BA'),
  ('Universidade Salvador', 'UNIFACS', 'BA'),
  -- CEARÁ
  ('Centro Universitário INTA-UNINTA - Sobral', 'UNINTA', 'CE'),
  ('Centro Universitário Unichristus - Fortaleza', 'UNICHRISTUS', 'CE'),
  ('Faculdade de Medicina Estácio de Juazeiro do Norte', 'ESTÁCIOFMJ', 'CE'),
  ('Universidade de Fortaleza', 'UNIFOR', 'CE'),
  ('Universidade Estadual do Ceará', 'UECE', 'CE'),
  ('Universidade Federal do Cariri - Barbalha', 'UFCA', 'CE'),
  ('Universidade Federal do Ceará', 'UFC', 'CE'),
  ('Universidade Federal do Ceará - Sobral', 'UFC-Sobral', 'CE'),
  ('Universidade Regional do Cariri', 'URCA', 'CE'),
  -- DISTRITO FEDERAL
  ('Centro Universitário de Brasília', 'UNICEUB', 'DF'),
  ('Centro Universitário do Planalto Central Apparecido dos Santos', 'UNICEPLAC', 'DF'),
  ('Centro Universitário Euro Americano', 'SCES-UNINEURO', 'DF'),
  ('Escola Superior de Ciências da Saúde - Brasília', 'ESCS', 'DF'),
  ('Universidade Católica de Brasília', 'UCB-DF', 'DF'),
  ('Universidade de Brasília', 'UnB', 'DF'),
  -- ESPÍRITO SANTO
  ('Faculdade Multivix Cachoeiro de Itapemirim', 'MULTIVIX-Cachoeiro', 'ES'),
  ('Centro Universitário do Espírito Santo - Colatina', 'UNESC-ES', 'ES'),
  ('Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória', 'EMESCAM', 'ES'),
  ('Faculdade Brasileira - Vitória', 'MULTIVIX VITORIA', 'ES'),
  ('Universidade Federal do Espírito Santo', 'UFES', 'ES'),
  ('Universidade Vila Velha', 'UVV', 'ES'),
  -- GOIÁS
  ('Centro de Ensino Superior Morgana Potrich', 'FAMP', 'GO'),
  ('Centro Universitário de Anápolis', 'UniEVANGÉLICA', 'GO'),
  ('Centro Universitário de Goiatuba', 'UNICERRADO', 'GO'),
  ('Centro Universitário de Mineiros', 'UNIFIMES', 'GO'),
  ('Centro Universitário de Mineiros - Trindade', 'UNIFIMES-Trindade', 'GO'),
  ('Faculdade Alfredo Nasser - Aparecida de Goiânia', 'UNIFAN', 'GO'),
  ('Pontifícia Universidade Católica de Goiás', 'PUC-GO', 'GO'),
  ('Universidade de Rio Verde - Aparecida de Goiânia', 'UniRV-Aparecida', 'GO'),
  ('Universidade de Rio Verde', 'UniRV', 'GO'),
  ('Universidade de Rio Verde - Goianésia', 'UniRV-Goianésia', 'GO'),
  ('Universidade de Rio Verde - Formosa', 'UniRV-Formosa', 'GO'),
  ('Universidade Estadual de Goiás - Itumbiara', 'UEG-Itumbiara', 'GO'),
  ('Universidade Federal de Goiás - Catalão', 'UFG-Catalão', 'GO'),
  ('Universidade Federal de Goiás - Jataí', 'UFG-Jataí', 'GO'),
  ('Universidade Federal de Goiás', 'UFG', 'GO'),
  -- MARANHÃO
  ('Centro Universitário Dom Bosco', 'UNDB', 'MA'),
  ('Faculdade de Ciências e Saúde Edufor', 'EDUFOR', 'MA'),
  ('Faculdade Pitágoras - Codó', 'Pitágoras-Codó', 'MA'),
  ('Universidade Ceuma - Imperatriz', 'UNICEUMA-Imperatriz', 'MA'),
  ('Universidade do Ceuma', 'UNICEUMA', 'MA'),
  ('Universidade Estadual do Maranhão - Caxias', 'UEMA', 'MA'),
  ('Universidade Federal do Maranhão - São Luís', 'UFMA', 'MA'),
  ('Universidade Federal do Maranhão - Pinheiro', 'UFMA-Pinheiro', 'MA'),
  ('Universidade Federal do Maranhão - Imperatriz', 'UFMA-Imperatriz', 'MA'),
  -- MINAS GERAIS
  ('Afya Faculdade de Ciências Médicas de Ipatinga', 'AFYA IPATINGA', 'MG'),
  ('Centro Universitário Atenas - Paracatu', 'UNIATENAS', 'MG'),
  ('Centro Universitário de Belo Horizonte', 'UNI-BH', 'MG'),
  ('Centro Universitário de Caratinga', 'UNEC', 'MG'),
  ('Centro Universitário de Manhuaçu', 'UNIFACIG', 'MG'),
  ('Centro Universitário de Patos de Minas', 'UNIPAM', 'MG'),
  ('Centro Universitário Presidente Tancredo de Almeida Neves - São João del Rei', 'UNIPTAN', 'MG'),
  ('Centro Universitário UNIFAGOC - Ubá', 'UNIFAGOC', 'MG'),
  ('Faculdade Atenas - Passos', 'ATENAS-PASSOS', 'MG'),
  ('Faculdade da Saúde e Ecologia Humana - Vespasiano', 'FASEH', 'MG'),
  ('Faculdade de Ciências Médicas de Minas Gerais', 'FCM-MG', 'MG'),
  ('Faculdade de Ciências Médicas e da Saúde de Juiz de Fora - Suprema', 'FCMS-JF', 'MG'),
  ('Faculdade de Medicina FATRA', 'FATRA', 'MG'),
  ('Faculdade de Medicina de Barbacena', 'FAME', 'MG'),
  ('Faculdade de Medicina de Itajubá', 'FMIt', 'MG'),
  ('Faculdade de Minas BH - FAMINAS', 'FAMINAS', 'MG'),
  ('Faculdade Dinâmica do Vale do Piranga - Ponte Nova', 'FADIP', 'MG'),
  ('Faculdade Sete Lagoas - Atenas', 'Atenas Sete Lagoas', 'MG'),
  ('Faculdade Vértice - Matipó', 'UNIVERTIIX', 'MG'),
  ('Universidade Federal de Viçosa', 'UFV', 'MG'),
  ('Instituto de Ciências da Saúde - Montes Claros', 'ICS-FUNORTE', 'MG'),
  ('Pontifícia Universidade Católica de Minas Gerais - Betim', 'PUC MINAS', 'MG'),
  ('Pontifícia Universidade Católica de Minas Gerais - Contagem', 'PUC-Contagem', 'MG'),
  ('Pontifícia Universidade Católica de Minas Gerais - Poços de Caldas', 'PUC-Poços', 'MG'),
  ('Uni-Faminas - Muriaé', 'UNI-FAMINAS Muriaé', 'MG'),
  ('Centro Universitário FIPMoc', 'FIP-MOC', 'MG'),
  ('Universidade de Itaúna', 'UIt', 'MG'),
  ('Universidade de Uberaba', 'UNIUBE', 'MG'),
  ('Universidade do Estado de Minas Gerais - Passos', 'UEMG-PASSOS', 'MG'),
  ('Universidade do Vale do Sapucaí - Pouso Alegre', 'UNIVAS', 'MG'),
  ('Universidade Estadual de Montes Claros', 'UNIMONTES', 'MG'),
  ('Universidade Federal de Alfenas', 'UNIFAL', 'MG'),
  ('Universidade Federal de Juiz de Fora - Governador Valadares', 'UFJF-GV', 'MG'),
  ('Universidade Federal de Juiz de Fora', 'UFJF', 'MG'),
  ('Universidade Federal de Lavras', 'UFLA', 'MG'),
  ('Universidade Federal de Minas Gerais', 'UFMG', 'MG'),
  ('Universidade Federal de Ouro Preto', 'UFOP', 'MG'),
  ('Universidade Federal de São João Del Rei', 'UFSJ', 'MG'),
  ('Universidade Federal de São João Del Rei - Divinópolis', 'UFSJ-Divinópolis', 'MG'),
  ('Universidade Federal de Uberlândia', 'UFU', 'MG'),
  ('Universidade Federal do Triângulo Mineiro - Uberaba', 'UFTM', 'MG'),
  ('Universidade Federal dos Vales do Jequitinhonha e Mucuri - Diamantina', 'UFVJM', 'MG'),
  ('Universidade Federal dos Vales do Jequitinhonha e Mucuri - Teófilo Otoni', 'UFVJM-TO', 'MG'),
  ('Universidade Presidente Antônio Carlos - Juiz de Fora', 'UNIPAC', 'MG'),
  ('Universidade Professor Edson Antônio Velano - Alfenas', 'UNIFENAS', 'MG'),
  ('Universidade Professor Edson Antônio Velano - Belo Horizonte', 'UNIFENAS-BH', 'MG'),
  ('Universidade Vale do Rio Doce', 'UNIVALE', 'MG'),
  -- MATO GROSSO DO SUL
  ('Universidade Anhanguera-Uniderp', 'UNIDERP', 'MS'),
  ('Universidade Estadual de Mato Grosso do Sul', 'UEMS', 'MS'),
  ('Universidade Federal da Grande Dourados', 'UFGD', 'MS'),
  ('Universidade Federal de Mato Grosso do Sul - Campo Grande', 'UFMS', 'MS'),
  ('Universidade Federal de Mato Grosso do Sul - Três Lagoas', 'UFMS-TL', 'MS'),
  -- MATO GROSSO
  ('Centro Universitário de Várzea Grande', 'UNIVAG', 'MT'),
  ('Centro Universitário do Vale do Araguaia', 'UNIVAR', 'MT'),
  ('Faculdade Estácio do Pantanal', 'FAPAN', 'MT'),
  ('Universidade de Cuiabá', 'UNIC', 'MT'),
  ('Universidade do Estado de Mato Grosso', 'UNEMAT', 'MT'),
  ('Universidade Federal de Mato Grosso', 'UFMT', 'MT'),
  ('Universidade Federal de Mato Grosso - Sinop', 'UFMT-Sinop', 'MT'),
  ('Universidade Federal de Mato Grosso - Rondonópolis', 'UFMT-Rondonópolis', 'MT'),
  -- PARÁ
  ('Afya Faculdade de Ciências Médicas de Abaetetuba', 'AFYA ABAETETUBA', 'PA'),
  ('Afya Faculdade de Ciências Médicas de Bragança', 'AFYA Bragança', 'PA'),
  ('Afya Faculdade de Ciências Médicas do Pará', 'FACIMPA', 'PA'),
  ('Centro Universitário do Estado do Pará', 'CESUPA', 'PA'),
  ('Faculdade de Ensino Superior da Amazônia Reunida', 'FESAR', 'PA'),
  ('Faculdade Metropolitana da Amazônia', 'FAMAZ', 'PA'),
  ('Universidade do Estado do Pará - Belém', 'UEPA', 'PA'),
  ('Universidade do Estado do Pará - Santarém', 'UEPA-Santarém', 'PA'),
  ('Universidade do Estado do Pará - Marabá', 'UEPA-Marabá', 'PA'),
  ('Universidade Federal do Pará', 'UFPA', 'PA'),
  -- PARAÍBA
  ('Afya Faculdade de Ciências Médicas da Paraíba', 'AFYA PARAÍBA', 'PB'),
  ('Centro Universitário de João Pessoa', 'UNIPÊ', 'PB'),
  ('Centro Universitário de Patos', 'UNIFIP', 'PB'),
  ('Centro Universitário Santa Maria - Cajazeiras', 'UNIFSM', 'PB'),
  ('Faculdade de Ciências Médicas de Campina Grande - Unifacisa', 'UNIFACISA', 'PB'),
  ('Faculdade de Medicina Nova Esperança - João Pessoa', 'FAMENE', 'PB'),
  ('Universidade Federal da Paraíba - João Pessoa', 'UFPB', 'PB'),
  ('Universidade Federal de Campina Grande - Cajazeiras', 'UFCG-Cajazeiras', 'PB'),
  ('Universidade Federal de Campina Grande', 'UFCG', 'PB'),
  -- PERNAMBUCO
  ('Afya Faculdade de Ciências Médicas de Garanhuns', 'FAMEG', 'PE'),
  ('Afya Faculdade de Ciências Médicas de Jaboatão dos Guararapes', 'AFYA JABOATAO', 'PE'),
  ('Centro Universitário Maurício de Nassau', 'UNINASSAU', 'PE'),
  ('Centro Universitário Tiradentes de Pernambuco', 'UNIT-PE', 'PE'),
  ('Faculdade de Ciências Aplicadas e Sociais de Petrolina', 'FACAPE', 'PE'),
  ('Faculdade de Medicina de Olinda', 'FMO', 'PE'),
  ('Faculdade de Medicina do Sertão', 'FMS', 'PE'),
  ('Faculdade Paraíso Araripina', 'FAP', 'PE'),
  ('Faculdade Pernambucana de Saúde - Recife', 'FPS', 'PE'),
  ('Faculdade Tiradentes de Goiana', 'FITS', 'PE'),
  ('Universidade Católica de Pernambuco', 'UNICAP', 'PE'),
  ('Universidade de Pernambuco - Serra Talhada', 'UPE-Serra Talhada', 'PE'),
  ('Universidade de Pernambuco - Recife', 'UPE', 'PE'),
  ('Universidade de Pernambuco - Garanhuns', 'UPE-Garanhuns', 'PE'),
  ('Universidade Federal de Pernambuco - Caruaru', 'UFPE-Caruaru', 'PE'),
  ('Universidade Federal de Pernambuco', 'UFPE', 'PE'),
  ('Universidade Federal do Vale do São Francisco - Petrolina', 'UNIVASF', 'PE'),
  -- PIAUÍ
  ('Centro Universitário Uninovafapi', 'UNINOVAFAPI', 'PI'),
  ('Faculdade de Ciências Humanas, Exatas e da Saúde do Piauí', 'FAHESP', 'PI'),
  ('Universidade Estadual do Piauí - Teresina', 'UESPI', 'PI'),
  ('Universidade Federal do Piauí', 'UFPI', 'PI'),
  ('Universidade Federal do Piauí - Picos', 'UFPI-Picos', 'PI'),
  ('Universidade Federal do Piauí - Parnaíba', 'UFPI-Parnaíba', 'PI'),
  -- PARANÁ
  ('Centro Universitário Assis Gurgacz - Cascavel', 'FAG', 'PR'),
  ('Centro Universitário Campo Real - Guarapuava', 'CAMPOREAL', 'PR'),
  ('Centro Universitário Ingá - Maringá', 'UNINGÁ', 'PR'),
  ('Centro Universitário Integrado de Campo Mourão', 'INTEGRADO-PR', 'PR'),
  ('Faculdade de Medicina de Toledo', 'UFPR-Toledo', 'PR'),
  ('Faculdade Evangélica Mackenzie do Paraná - Curitiba', 'FEMPAR', 'PR'),
  ('Faculdades Pequeno Príncipe - Curitiba', 'FPP', 'PR'),
  ('Pontifícia Universidade Católica do Paraná - Curitiba', 'PUCPR', 'PR'),
  ('Pontifícia Universidade Católica do Paraná - Londrina', 'PUCPR-Londrina', 'PR'),
  ('Pontifícia Universidade Católica do Paraná - Toledo', 'PUCPR-Toledo', 'PR'),
  ('UNIVEL Centro Universitário', 'UNIVEL', 'PR'),
  ('Universidade de Maringá - CESUMAR', 'UNICESUMAR', 'PR'),
  ('Universidade de Pato Branco', 'UNIDEP', 'PR'),
  ('Universidade Estadual de Londrina', 'UEL', 'PR'),
  ('Universidade Estadual de Maringá', 'UEM', 'PR'),
  ('Universidade Estadual de Ponta Grossa', 'UEPG', 'PR'),
  ('Universidade Estadual do Centro Oeste - Guarapuava', 'UNICENTRO', 'PR'),
  ('Universidade Estadual do Oeste do Paraná - Francisco Beltrão', 'UNIOESTE-FB', 'PR'),
  ('Universidade Estadual do Oeste do Paraná - Cascavel', 'UNIOESTE', 'PR'),
  ('Universidade Federal da Integração Latino-Americana - Foz do Iguaçu', 'UNILA', 'PR'),
  ('Universidade Federal do Paraná - Toledo', 'UFPR-Toledo-Fed', 'PR'),
  ('Universidade Federal do Paraná - Curitiba', 'UFPR', 'PR'),
  ('Universidade Paranaense - Umuarama', 'UNIPAR', 'PR'),
  ('Universidade Positivo - Curitiba', 'UP', 'PR'),
  -- RIO DE JANEIRO
  ('Centro Universitário de Valença', 'UNIFAA', 'RJ'),
  ('Centro Universitário de Volta Redonda', 'UniFOA', 'RJ'),
  ('Centro Universitário Redentor - Itaperuna', 'UNIREDENTOR', 'RJ'),
  ('Centro Universitário Serra dos Órgãos - Teresópolis', 'UNIFESO', 'RJ'),
  ('Escola de Medicina Souza Marques - Rio de Janeiro', 'EMSM', 'RJ'),
  ('Faculdade de Medicina de Campos', 'FMC', 'RJ'),
  ('Faculdade de Medicina de Petrópolis', 'UNIFASE', 'RJ'),
  ('Faculdade Metropolitana São Carlos - Bom Jesus do Itabapoana', 'FAMESC', 'RJ'),
  ('Faculdade União Araruama de Ensino', 'FAC-UNILAGOS', 'RJ'),
  ('Suprema Faculdade de Ciências Médicas de Três Rios', 'FCM-TR', 'RJ'),
  ('Universidade Castelo Branco', 'UCB-RJ', 'RJ'),
  ('Universidade de Vassouras', 'UNIVASSOURAS', 'RJ'),
  ('Universidade do Estado do Rio de Janeiro', 'UERJ', 'RJ'),
  ('Universidade do Grande Rio - Duque de Caxias', 'UNIGRANRIO-DC', 'RJ'),
  ('Universidade do Grande Rio', 'UNIGRANRIO', 'RJ'),
  ('Universidade Estácio de Sá - Angra dos Reis', 'UNESA-Angra', 'RJ'),
  ('Universidade Estácio de Sá - Campus João Uchôa', 'UNESA-JU', 'RJ'),
  ('Universidade Estácio de Sá', 'UNESA', 'RJ'),
  ('Universidade Federal do Estado do Rio de Janeiro', 'UNIRIO', 'RJ'),
  ('Universidade Federal do Rio de Janeiro', 'UFRJ', 'RJ'),
  ('Universidade Federal do Rio de Janeiro - Macaé', 'UFRJ-Macaé', 'RJ'),
  ('Universidade Federal Fluminense - Niterói', 'UFF', 'RJ'),
  ('Universidade Iguaçu - Itaperuna', 'UNIG-Itaperuna', 'RJ'),
  ('Universidade Iguaçu - Nova Iguaçu', 'UNIG-NI', 'RJ'),
  ('Universidade Veiga de Almeida', 'UVA', 'RJ'),
  -- RIO GRANDE DO NORTE
  ('Faculdade Nova Esperança de Mossoró', 'FACENE-RN', 'RN'),
  ('Universidade do Estado do Rio Grande do Norte - Mossoró', 'UERN', 'RN'),
  ('Universidade Federal do Rio Grande do Norte', 'UFRN', 'RN'),
  ('Universidade Federal do Rio Grande do Norte - Caicó', 'UFRN-Caicó', 'RN'),
  ('Universidade Federal Rural do Semi-Árido - Mossoró', 'UFERSA', 'RN'),
  ('Universidade Potiguar', 'UnP', 'RN'),
  -- RONDÔNIA
  ('Centro Universitário Aparício Carvalho', 'FIMCA', 'RO'),
  ('Centro Universitário São Lucas - Porto Velho', 'UniSL', 'RO'),
  ('Centro Universitário UNIFACIMED', 'FACIMED', 'RO'),
  ('Faculdade de Educação e Cultura de Vilhena', 'UNESC-RO', 'RO'),
  ('Faculdades Integradas Aparício Carvalho - Porto Velho', 'FINCA', 'RO'),
  ('Universidade Federal de Rondônia', 'UNIR', 'RO'),
  -- RORAIMA
  ('Universidade Estadual de Roraima', 'UERR', 'RR'),
  ('Universidade Federal de Roraima', 'UFRR', 'RR'),
  -- RIO GRANDE DO SUL
  ('Centro Universitário Univates - Lajeado', 'UNIVATES', 'RS'),
  ('Pontifícia Universidade Católica do Rio Grande do Sul', 'PUCRS', 'RS'),
  ('Universidade Católica de Pelotas', 'UCPEL', 'RS'),
  ('Universidade de Caxias do Sul', 'UCS', 'RS'),
  ('Universidade de Passo Fundo', 'UPF', 'RS'),
  ('Universidade de Santa Cruz do Sul', 'UNISC', 'RS'),
  ('Universidade do Vale do Rio dos Sinos - São Leopoldo', 'UNISINOS', 'RS'),
  ('Universidade Federal da Fronteira Sul - Passo Fundo', 'UFFS-PF', 'RS'),
  ('Universidade Federal de Ciências da Saúde de Porto Alegre', 'UFCSPA', 'RS'),
  ('Universidade Federal de Pelotas', 'UFPel', 'RS'),
  ('Universidade Federal de Santa Maria', 'UFSM', 'RS'),
  ('Universidade Federal do Pampa - Uruguaiana', 'UNIPAMPA', 'RS'),
  ('Universidade Federal do Rio Grande do Sul', 'UFRGS', 'RS'),
  ('Universidade Federal do Rio Grande', 'FURG', 'RS'),
  ('Universidade Feevale - Novo Hamburgo', 'FEEVALE', 'RS'),
  ('Universidade Franciscana - Santa Maria', 'UFN', 'RS'),
  ('Universidade Luterana do Brasil - Canoas', 'ULBRA', 'RS'),
  ('Universidade Regional do Noroeste do Estado do RS', 'UNIJUÍ', 'RS'),
  ('Universidade Regional Integrada do Alto Uruguai - Erechim', 'URI ERECHIM', 'RS'),
  -- SANTA CATARINA
  ('Centro Universitário para o Desenvolvimento do Alto Vale do Itajaí', 'UNIDAVI', 'SC'),
  ('Faculdade Estácio de Jaraguá do Sul', 'Estácio-Jaraguá', 'SC'),
  ('Faculdade Life Unic Education', 'Lifeunicedu', 'SC'),
  ('Universidade Alto Vale do Rio do Peixe', 'UNIARP', 'SC'),
  ('Universidade Comunitária da Região de Chapecó', 'UNOCHAPECÓ', 'SC'),
  ('Universidade da Região de Joinville', 'UNIVILLE', 'SC'),
  ('Universidade de Brusque', 'UNIFEBE', 'SC'),
  ('Universidade do Contestado - Mafra', 'UnC', 'SC'),
  ('Universidade do Extremo Sul Catarinense - Criciúma', 'UNESC-SC', 'SC'),
  ('Universidade do Oeste de Santa Catarina - Joaçaba', 'UNOESC', 'SC'),
  ('Universidade do Planalto Catarinense - Lages', 'UNIPLAC', 'SC'),
  ('Universidade do Sul de Santa Catarina - Palhoça', 'UNISUL-Palhoça', 'SC'),
  ('Universidade do Sul de Santa Catarina - Tubarão', 'UNISUL-Tubarão', 'SC'),
  ('Universidade do Vale do Itajaí', 'UNIVALI', 'SC'),
  ('Universidade Federal da Fronteira Sul - Chapecó', 'UFFS-Chapecó', 'SC'),
  ('Universidade Federal de Santa Catarina - Araranguá', 'UFSC-Araranguá', 'SC'),
  ('Universidade Federal de Santa Catarina', 'UFSC', 'SC'),
  ('Universidade Regional de Blumenau', 'FURB', 'SC'),
  -- SERGIPE
  ('Universidade Federal de Sergipe', 'UFS', 'SE'),
  ('Universidade Federal de Sergipe - Lagarto', 'UFS-Lagarto', 'SE'),
  ('Universidade Tiradentes', 'UNIT', 'SE'),
  ('Universidade Tiradentes - Estância', 'UNIT-Estância', 'SE'),
  -- SÃO PAULO
  ('Centro Universitário Barão de Mauá - Ribeirão Preto', 'UFBM', 'SP'),
  ('Centro Universitário Campo Limpo Paulista', 'UNIFACCAMP', 'SP'),
  ('Centro Universitário Católico Salesiano - Araçatuba', 'UNISALESIANO', 'SP'),
  ('Centro Universitário Claretiano - Rio Claro', 'CEUCLAR', 'SP'),
  ('Centro Universitário das Faculdades Associadas de Ensino - São João da Boa Vista', 'UNIFAE', 'SP'),
  ('Centro Universitário de Adamantina', 'FAI', 'SP'),
  ('Centro Universitário de Araraquara', 'UNIARA', 'SP'),
  ('Centro Universitário de Indaiatuba', 'UniMax', 'SP'),
  ('Centro Universitário de Jaguariúna', 'UNIFAJ', 'SP'),
  ('Centro Universitário de Santa Fé do Sul', 'UNIFUNEC', 'SP'),
  ('Centro Universitário de Votuporanga', 'UNIFEV', 'SP'),
  ('Centro Universitário Estácio de Ribeirão Preto', 'UNISEB', 'SP'),
  ('Centro Universitário Lusíada - Santos', 'UNILUS', 'SP'),
  ('Centro Universitário Municipal de Franca', 'UNI-FACEF', 'SP'),
  ('Centro Universitário Padre Albino - Catanduva', 'UNIFIPA', 'SP'),
  ('Centro Universitário São Camilo - São Paulo', 'SÃO CAMILO', 'SP'),
  ('Centro Universitário Sudoeste Paulista', 'UniFSP', 'SP'),
  ('Faculdade das Américas - São Paulo', 'FAM-SP', 'SP'),
  ('Faculdade de Ciências da Saúde de Barretos Dr. Paulo Prata', 'FACISB', 'SP'),
  ('Faculdade de Ciências da Saúde Sírio-Libanês', 'FSL', 'SP'),
  ('Faculdade de Ciências Médicas da Santa Casa de São Paulo', 'FCMSCSP', 'SP'),
  ('Faculdade de Ciências Médicas de São José dos Campos - Humanitas', 'HUMANITAS', 'SP'),
  ('Faculdade de Medicina - Unoeste - Guarujá', 'Medicina-Guarujá', 'SP'),
  ('Faculdade de Medicina de Jundiaí', 'FMJ', 'SP'),
  ('Faculdade de Medicina de Marília', 'FAMEMA', 'SP'),
  ('Faculdade de Medicina de Penápolis', 'FUNEPE', 'SP'),
  ('Faculdade de Medicina de São José do Rio Preto', 'FAMERP', 'SP'),
  ('Faculdade de Medicina do ABC', 'FMABC', 'SP'),
  ('Faculdade de Medicina FACERES - São José do Rio Preto', 'FACERES', 'SP'),
  ('Faculdade Israelita de Ciências da Saúde Albert Einstein', 'Einstein', 'SP'),
  ('Faculdade Municipal Prof. Franco Montoro - Mogi Guaçu', 'FMPFM', 'SP'),
  ('Faculdade Santa Marcelina', 'FASM', 'SP'),
  ('Faculdade São Leopoldo Mandic - Araras', 'FSLM-Araras', 'SP'),
  ('Faculdade São Leopoldo Mandic - Campinas', 'SLMANDIC', 'SP'),
  ('Faculdade São Leopoldo Mandic - Limeira', 'SLM-Limeira', 'SP'),
  ('Faculdade Unifadra - Dracena', 'UNIFADRA', 'SP'),
  ('Fundação Educacional do Município de Assis', 'FEMA', 'SP'),
  ('Pontifícia Universidade Católica de Campinas', 'PUC-CAMPINAS', 'SP'),
  ('Pontifícia Universidade Católica de São Paulo - Sorocaba', 'PUCSP-Sorocaba', 'SP'),
  ('União das Faculdades dos Grandes Lagos - São José do Rio Preto', 'UNILAGO', 'SP'),
  ('Universidade Anhembi Morumbi - São Paulo', 'UAM', 'SP'),
  ('Universidade Anhembi Morumbi - Piracicaba', 'UAM-Piracicaba', 'SP'),
  ('Universidade Anhembi Morumbi - São José dos Campos', 'UAM-SJC', 'SP'),
  ('Universidade Brasil - Fernandópolis', 'UB', 'SP'),
  ('Universidade Cidade de São Paulo', 'UNICID', 'SP'),
  ('Universidade de Franca', 'UNIFRAN', 'SP'),
  ('Universidade de Marília', 'UNIMAR', 'SP'),
  ('Universidade de Mogi das Cruzes', 'UMC', 'SP'),
  ('Universidade de Ribeirão Preto', 'UNAERP', 'SP'),
  ('Universidade de Ribeirão Preto - Guarujá', 'UNAERP-Guarujá', 'SP'),
  ('Universidade de Santo Amaro', 'UNISA', 'SP'),
  ('Universidade de São Caetano do Sul', 'USCS', 'SP'),
  ('Universidade de São Paulo - Ribeirão Preto', 'USP-RP', 'SP'),
  ('Universidade de São Paulo', 'USP-SP', 'SP'),
  ('Universidade de São Paulo - Bauru', 'USP-Bauru', 'SP'),
  ('Universidade de Taubaté', 'UNITAU', 'SP'),
  ('Universidade do Oeste Paulista - Jaú', 'UNOESTE-Jaú', 'SP'),
  ('Universidade do Oeste Paulista - Presidente Prudente', 'UNOESTE', 'SP'),
  ('Universidade Estadual de Campinas', 'UNICAMP', 'SP'),
  ('Universidade Estadual Paulista - Botucatu', 'UNESP', 'SP'),
  ('Universidade Federal de São Carlos', 'UFSCAR', 'SP'),
  ('Universidade Federal de São Paulo', 'UNIFESP', 'SP'),
  ('Universidade Metropolitana de Santos', 'UNIMES', 'SP'),
  ('Universidade Municipal de São Caetano do Sul - Bela Vista', 'USCS-BV', 'SP'),
  ('Universidade Municipal de São Caetano do Sul', 'USCS-SC', 'SP'),
  ('Universidade Nove de Julho - São Bernardo do Campo', 'UNINOVE-SBC', 'SP'),
  ('Universidade Nove de Julho - São Paulo', 'UNINOVE', 'SP'),
  ('Universidade Nove de Julho - Mauá', 'UNINOVE-Mauá', 'SP'),
  ('Universidade Nove de Julho - Osasco', 'UNINOVE-Osasco', 'SP'),
  ('Universidade Nove de Julho - Guarulhos', 'UNINOVE-Guarulhos', 'SP'),
  ('Universidade São Francisco - Bragança Paulista', 'USF', 'SP'),
  ('Universidade São Judas Tadeu', 'USJT', 'SP'),
  -- TOCANTINS
  ('Centro Universitário UnirG - Gurupi', 'UNIRG', 'TO'),
  ('Centro Universitário Tocantinense Presidente Antônio Carlos', 'UNITPAC', 'TO'),
  ('Faculdade Presidente Antônio Carlos - Porto Nacional', 'FAPAC', 'TO'),
  ('Instituto Presidente Antônio Carlos - Palmas', 'ITPAC-Palmas', 'TO'),
  ('Universidade de Gurupi - Paraíso', 'UNIRG-Paraíso', 'TO'),
  ('Universidade Estadual do Tocantins', 'Unitins', 'TO'),
  ('Universidade Federal do Tocantins - Araguaína', 'UFT-Araguaína', 'TO'),
  ('Universidade Federal do Tocantins - Palmas', 'UFT', 'TO')
ON CONFLICT (abbreviation) DO NOTHING;
